# Generated by Django 2.2.7 on 2024-07-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_savedcarts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DinnerPlatters',
            new_name='beverage',
        ),
    ]
