# Generated by Django 2.2.7 on 2024-07-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20240707_0811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salad',
            new_name='Snack',
        ),
    ]
