# Generated by Django 2.2.7 on 2024-07-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20240707_0820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasta',
            new_name='Chinese',
        ),
    ]
